### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Instinkt-Servers** [dan335/dominus#20]
On "docker build /home/dominus" i get this Error on Step 6:

Step 6/13 : ADD .build/dominus.tar.gz /opt/app/
ADD failed: stat /var/lib/docker/tmp/docker-builder145485930/.build/dominus.tar.gz: no such file or directory

Also with a clear install.

**Comment by dan335** [comment]
Looks like you need to build it first.

meteor build .build --architecture os.linux.x86_64

take a look at deploy.sh

**Comment by bammertine** [comment]
./deploy.sh is Login as User "danphi" and requires a password on gitlab.
Do i have to replace this with my User or ... ?

**Comment by bammertine** [comment]
Same Error after "meteor build .build --architecture os.linux.x86_64".


Step 6/13 : ADD .build/dominus.tar.gz /opt/app/
ADD failed: stat /var/lib/docker/tmp/docker-builder357900194/.build/dominus.tar.gz: no such file or directory

**Comment by bammertine** [comment]
I also get this Errors:


The push refers to repository [registry.gitlab.com/danphi/dominus]
An image does not exist locally with the tag: registry.gitlab.com/danphi/dominus
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git


Is this still on gitlab?

**Comment by bammertine** [comment]
It doesnt matter what i try. It doesnt work for me.

creating with meteor:
`=> Started proxy.
=> Meteor 1.8.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
W20190429-16:16:39.175(0)? (STDERR) Note: you are using a pure-JavaScript implem                                                                                                                  entation of bcrypt.
W20190429-16:16:39.967(0)? (STDERR) While this implementation will work correctl                                                                                                                  y, it is known to be
W20190429-16:16:39.967(0)? (STDERR) approximately three times slower than the na                                                                                                                  tive implementation.
W20190429-16:16:39.967(0)? (STDERR) In order to use the native implementation in                                                                                                                  stead, run
W20190429-16:16:39.967(0)? (STDERR)
W20190429-16:16:39.968(0)? (STDERR)   meteor npm install --save bcrypt
W20190429-16:16:39.968(0)? (STDERR)
W20190429-16:16:39.968(0)? (STDERR) in the root directory of your application.
W20190429-16:17:04.044(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.7.1-rc                                                                                                                  .0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-                                                                                                                  os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190429-16:17:04.046(0)? (STDERR)                                            t                                                                                                                  hrow(ex);
W20190429-16:17:04.048(0)? (STDERR)                                            ^
W20190429-16:17:04.049(0)? (STDERR)
W20190429-16:17:04.050(0)? (STDERR) TypeError: Cannot read property 'bucket' of                                                                                                                   undefined
W20190429-16:17:04.050(0)? (STDERR)     at mapbaker.js (packages/dominus-mapbake                                                                                                                  r/mapbaker.js:14:39)
W20190429-16:17:04.052(0)? (STDERR)     at fileEvaluate (packages/modules-runtim                                                                                                                  e.js:322:7)
W20190429-16:17:04.052(0)? (STDERR)     at Module.require (packages/modules-runt                                                                                                                  ime.js:224:14)
W20190429-16:17:04.053(0)? (STDERR)     at require (packages/modules-runtime.js:                                                                                                                  244:21)
W20190429-16:17:04.053(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:597:1
W20190429-16:17:04.053(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:604:3
W20190429-16:17:04.053(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:411:36
W20190429-16:17:04.054(0)? (STDERR)     at Array.forEach (<anonymous>)
W20190429-16:17:04.054(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:220:19
W20190429-16:17:04.054(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:471:5
W20190429-16:17:04.055(0)? (STDERR)     at Function.run (/home/dominus-master/.m                                                                                                                  eteor/local/build/programs/server/profile.js:510:12)
W20190429-16:17:04.055(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:470:11
=> Exited with code: 1
W20190429-16:17:07.552(0)? (STDERR) Note: you are using a pure-JavaScript implem                                                                                                                  entation of bcrypt.
W20190429-16:17:07.552(0)? (STDERR) While this implementation will work correctl                                                                                                                  y, it is known to be
W20190429-16:17:07.553(0)? (STDERR) approximately three times slower than the na                                                                                                                  tive implementation.
W20190429-16:17:07.553(0)? (STDERR) In order to use the native implementation in                                                                                                                  stead, run
W20190429-16:17:07.553(0)? (STDERR)
W20190429-16:17:07.553(0)? (STDERR)   meteor npm install --save bcrypt
W20190429-16:17:07.553(0)? (STDERR)
W20190429-16:17:07.553(0)? (STDERR) in the root directory of your application.
=> Finished delayed build of web.browser.legacy in 1986ms
W20190429-16:17:09.872(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.7.1-rc                                                                                                                  .0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-                                                                                                                  os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190429-16:17:09.876(0)? (STDERR)                                            t                                                                                                                  hrow(ex);
W20190429-16:17:09.876(0)? (STDERR)                                            ^
W20190429-16:17:09.877(0)? (STDERR)
W20190429-16:17:09.877(0)? (STDERR) TypeError: Cannot read property 'bucket' of                                                                                                                   undefined
W20190429-16:17:09.877(0)? (STDERR)     at mapbaker.js (packages/dominus-mapbake                                                                                                                  r/mapbaker.js:14:39)
W20190429-16:17:09.877(0)? (STDERR)     at fileEvaluate (packages/modules-runtim                                                                                                                  e.js:322:7)
W20190429-16:17:09.877(0)? (STDERR)     at Module.require (packages/modules-runt                                                                                                                  ime.js:224:14)
W20190429-16:17:09.877(0)? (STDERR)     at require (packages/modules-runtime.js:                                                                                                                  244:21)
W20190429-16:17:09.878(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:597:1
W20190429-16:17:09.878(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:604:3
W20190429-16:17:09.878(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:411:36
W20190429-16:17:09.878(0)? (STDERR)     at Array.forEach (<anonymous>)
W20190429-16:17:09.878(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:220:19
W20190429-16:17:09.878(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:471:5
W20190429-16:17:09.878(0)? (STDERR)     at Function.run (/home/dominus-master/.m                                                                                                                  eteor/local/build/programs/server/profile.js:510:12)
W20190429-16:17:09.879(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:470:11
=> Exited with code: 1
W20190429-16:17:12.216(0)? (STDERR) Note: you are using a pure-JavaScript implem                                                                                                                  entation of bcrypt.
W20190429-16:17:12.218(0)? (STDERR) While this implementation will work correctl                                                                                                                  y, it is known to be
W20190429-16:17:12.220(0)? (STDERR) approximately three times slower than the na                                                                                                                  tive implementation.
W20190429-16:17:12.221(0)? (STDERR) In order to use the native implementation in                                                                                                                  stead, run
W20190429-16:17:12.221(0)? (STDERR)
W20190429-16:17:12.221(0)? (STDERR)   meteor npm install --save bcrypt
W20190429-16:17:12.221(0)? (STDERR)
W20190429-16:17:12.221(0)? (STDERR) in the root directory of your application.
=> Finished delayed build of web.browser.legacy in 1716ms
W20190429-16:17:14.383(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.7.1-rc                                                                                                                  .0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-                                                                                                                  os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190429-16:17:14.384(0)? (STDERR)                                            t                                                                                                                  hrow(ex);
W20190429-16:17:14.384(0)? (STDERR)                                            ^
W20190429-16:17:14.384(0)? (STDERR)
W20190429-16:17:14.385(0)? (STDERR) TypeError: Cannot read property 'bucket' of                                                                                                                   undefined
W20190429-16:17:14.385(0)? (STDERR)     at mapbaker.js (packages/dominus-mapbake                                                                                                                  r/mapbaker.js:14:39)
W20190429-16:17:14.385(0)? (STDERR)     at fileEvaluate (packages/modules-runtim                                                                                                                  e.js:322:7)
W20190429-16:17:14.385(0)? (STDERR)     at Module.require (packages/modules-runt                                                                                                                  ime.js:224:14)
W20190429-16:17:14.385(0)? (STDERR)     at require (packages/modules-runtime.js:                                                                                                                  244:21)
W20190429-16:17:14.386(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:597:1
W20190429-16:17:14.386(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/packages/dominus-mapbaker.js:604:3
W20190429-16:17:14.386(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:411:36
W20190429-16:17:14.386(0)? (STDERR)     at Array.forEach (<anonymous>)
W20190429-16:17:14.386(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:220:19
W20190429-16:17:14.386(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:471:5
W20190429-16:17:14.387(0)? (STDERR)     at Function.run (/home/dominus-master/.m                                                                                                                  eteor/local/build/programs/server/profile.js:510:12)
W20190429-16:17:14.388(0)? (STDERR)     at /home/dominus-master/.meteor/local/bu                                                                                                                  ild/programs/server/boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
`

Install Bcrypt:

npm WARN deprecated bcrypt@0.8.7: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes

> bcrypt@0.8.7 install /home/dominus-master/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/home/dominus-master/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
bcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/blowfish.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory '/home/dominus-master/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.meteor/packages/meteor-tool/.1.7.1-rc.0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-862.9.1.vz7.63.3
gyp ERR! command "/root/.meteor/packages/meteor-tool/.1.7.1-rc.0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/root/.meteor/packages/meteor-tool/.1.7.1-rc.0.1mlvqx8.7hslk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dominus-master/node_modules/bcrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-29T16_36_13_031Z-debug.log


Nothing seems to work

**Comment by Instinkt-Servers** [comment]
Found my Problem. My Meteor was broken. Reinstall and its working well.

**Comment by Instinkt-Servers** [comment]
When i run my File now i get this Error from Docker:

/opt/app/bundle/programs/server/node_modules/fibers/fibers.js:90
                                        return fn.apply(this, arguments);
                                                  ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1378:11)
    at runWebAppServer (packages/webapp/webapp_server.js:771:18)
    at webapp_server.js (packages/webapp/webapp_server.js:1175:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/app/bundle/programs/server/packages/webapp.js:1588:15
    at /opt/app/bundle/programs/server/packages/webapp.js:1597:3
    at /opt/app/bundle/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /opt/app/bundle/programs/server/boot.js:228:19
    at /opt/app/bundle/programs/server/boot.js:479:5
    at Function.run (/opt/app/bundle/programs/server/profile.js:510:12)
    at /opt/app/bundle/programs/server/boot.js:478:11


Where do i have to set ROOT_URL?

**Comment by dan335** [comment]
ROOT_URL is a Meteor environment variable.

https://docs.meteor.com/environment-variables.html#ROOT-URL
